"""Create initial tables

Revision ID: dd2cc92f9656
Revises: 02de0d1afa4a
Create Date: 2025-10-16 15:47:00.839077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2cc92f9656'
down_revision: Union[str, Sequence[str], None] = '02de0d1afa4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sensor_data_timestamp_idx'), table_name='sensor_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('sensor_data_timestamp_idx'), 'sensor_data', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
